version: '3.8'

services:
  app:
    depends_on:
      - db
    build: ./
    ports:
      - "1323:1323"
    networks:
      - mynet
    restart: on-failure

  db:
    container_name: postgres-picture
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - mynet
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres-picture:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - roach:/var/lib/postgresql/data
      - ./migrations:/flyway/sql
    depends_on:
      - db
    networks:
      - mynet

volumes:
  roach:

networks:
  mynet:
    driver: bridge